//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rỗng&gt;.
        /// </summary>
        public static string EMPTY_ITEM {
            get {
                return ResourceManager.GetString("EMPTY_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string ERROR_CAPTION {
            get {
                return ResourceManager.GetString("ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string INFOR_CAPTION {
            get {
                return ResourceManager.GetString("INFOR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        public static string MB_FAILURE {
            get {
                return ResourceManager.GetString("MB_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string MB_SUCCESS {
            get {
                return ResourceManager.GetString("MB_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM.
        /// </summary>
        public static string PM_CASH {
            get {
                return ResourceManager.GetString("PM_CASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK.
        /// </summary>
        public static string PM_TRANSFER {
            get {
                return ResourceManager.GetString("PM_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM/CK.
        /// </summary>
        public static string PM_UNIDENTIFY {
            get {
                return ResourceManager.GetString("PM_UNIDENTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string SIZE_L {
            get {
                return ResourceManager.GetString("SIZE_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string SIZE_M {
            get {
                return ResourceManager.GetString("SIZE_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SIZE_S {
            get {
                return ResourceManager.GetString("SIZE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL.
        /// </summary>
        public static string SIZE_XL {
            get {
                return ResourceManager.GetString("SIZE_XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXL.
        /// </summary>
        public static string SIZE_XXL {
            get {
                return ResourceManager.GetString("SIZE_XXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XXXL.
        /// </summary>
        public static string SIZE_XXXL {
            get {
                return ResourceManager.GetString("SIZE_XXXL", resourceCulture);
            }
        }
    }
}
