<?xml version="1.0" encoding="utf-8"?><Database Name="UShopDB" Class="UShopDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ALIENWARE\SQLEXPRESS;Initial Catalog=UShopDB;Integrated Security=True" SettingsObjectName="Model.Properties.Settings" SettingsPropertyName="UShopDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNT" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="ACC_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACC_CODE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.APPOINTMENT" Member="APPOINTMENTs">
    <Type Name="APPOINTMENT">
      <Column Name="APP_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="APP_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PREPARER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="APP_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CATEGORY" Member="CATEGORies">
    <Type Name="CATEGORY">
      <Column Name="CATEGORY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CATEGORY_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CATEGORY_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="CUS_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CUS_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CUS_NAME" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="BOUGHT_AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE" Member="EMPLOYEEs">
    <Type Name="EMPLOYEE">
      <Column Name="EMP_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMP_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="EMP_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GENDER" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="BIRTHDAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID_CARD_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="APPROVE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WORK_STATUS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SEV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="POSITION" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.INVOICE" Member="INVOICEs">
    <Type Name="INVOICE">
      <Column Name="INVOICE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INVOICE_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="BUYER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SELLER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYMENT_METHOD" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_PAYMENT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_SALE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="VAT_RATE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="VAT_AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.INVOICE_ITEM" Member="INVOICE_ITEMs">
    <Type Name="INVOICE_ITEM">
      <Column Name="INVOICE_ITEM_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="INVOICE_ITEM_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="INVOICE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SIZE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DISCOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PRODUCT_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="CATEGORY_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRODUCT_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SELLING_PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COST_PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SALE_AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PRODUCER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ORIGIN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IMAGE_SRC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT_SIZE" Member="PRODUCT_SIZEs">
    <Type Name="PRODUCT_SIZE">
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SIZE" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IN_STOCK_QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIPT_NOTE" Member="RECEIPT_NOTEs">
    <Type Name="RECEIPT_NOTE">
      <Column Name="RN_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RN_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SUPPLIER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PREPARER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISSUED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACCOUNTING_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACCOUNTED" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIPT_NOTE_ITEM" Member="RECEIPT_NOTE_ITEMs">
    <Type Name="RECEIPT_NOTE_ITEM">
      <Column Name="RN_ITEM_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RN_ITEM_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="RN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRODUCT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_STOCK_S" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_VOUCHER_S" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_STOCK_M" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_VOUCHER_M" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_STOCK_L" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_VOUCHER_L" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_STOCK_XL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_VOUCHER_XL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_STOCK_XXL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_VOUCHER_XXL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TOTAL_STOCK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_VOUCHER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SUPPLIER" Member="SUPPLIERs">
    <Type Name="SUPPLIER">
      <Column Name="SUPPLIER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SUPPLIER_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SUPPLIER_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TAX_CODE" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PHONE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ADDRESS" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="RECORD_STATUS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>